### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by PatrickFeng** [yblin/Supervoxel-for-3D-point-clouds#2]
Hi Lin,

Thanks for your excellent work. I did not find the code of evaluation in your repo. Could you share it?

**Comment by yblin** [comment]
The evaluation metrics depend on ground truth.

And, it is not difficult to write the evaluation code. I have no plans to provide this code currently.

**Comment by PatrickFeng** [comment]
> The evaluation metrics depend on ground truth.
> 
> And, it is not difficult to write the evaluation code. I have no plans to provide this code currently.

Thanks for your reply.
