### ISSUE TITLE
extreme long running time 

### ISSUE THREAD

**Issue by codefortheplanet** [yblin/Supervoxel-for-3D-point-clouds#6]
@yblin Thank you for the great work and I am trying to use it for my dataset. It only has 256958 points but now has been already running for 74 hours and no results have been generated yet. Could you let me know which parameter(s) I can adjust to make it run in a reasonable timeframe? Thanks.

**Comment by bramdekker** [comment]
You probably have to decrease the seed resolution (e.g. resolution variable on line 116 in main.cc), so more supervoxels will be expected. I ran into the problem that the lambda variable increased to infinity and overflowed, thereby not decreasing (no merging) the number of supervoxels anymore and thus looping infinitely. I would suggest starting with quite a low seed resolution like 0.01. Also, do not forget to keep the voxel resolution lower than half the seed resolution.

**Comment by yblin** [comment]
> You probably have to decrease the seed resolution (e.g. resolution variable on line 116 in main.cc), so more supervoxels will be expected. I ran into the problem that the lambda variable increased to infinity and overflowed, thereby not decreasing (no merging) the number of supervoxels anymore and thus looping infinitely. I would suggest starting with quite a low seed resolution like 0.01. Also, do not forget to keep the voxel resolution lower than half the seed resolution.

Thanks bramdekker for pointing out this issue. I simply added a finish lambda to solve this problem.

**Comment by codefortheplanet** [comment]
@bramdekker Thanks for providing your insights and the issue has been resolved using a low seed resolution.  
@yblin Thanks for making the update.
